language: node_js
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      node_js: "4"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "6"
    - os: linux
      dist: trusty
      sudo: false
      node_js: "8"
    - os: osx
      osx_image: xcode8.3
      node_js: "4"
    - os: osx
      osx_image: xcode8.3
      node_js: "6"
    - os: osx
      osx_image: xcode8.3
      node_js: "8"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sysctl -a | grep machdep.cpu; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cat /proc/cpuinfo; gcc -march=native -E -v - </dev/null 2>&1 | grep cc1; fi
env:
  global:
    - CXXFLAGS="-march=corei7 -mno-avx -mno-aes -mno-f16c"
